config/routes.rb
Buffset::Application.routes.draw do
  # Omniauth pure
  match "/signin" => "services#signin"
  match "/signout" => "services#signout"

  match '/auth/:service/callback' => 'services#create'
  match '/auth/failure' => 'services#failure'

  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'signup'
      post 'newaccount'
      get 'failure'
    end
  end

  # used for the demo application only

  resources :users, :only => [:index, :show, :edit, :update] do
    collection do
      get 'index'
    end
  end

  root :to => "services#signin"
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Buffset
    %link{:href => 'http://fonts.googleapis.com/css?family=Walter+Turncoat&v2', :rel => 'stylesheet', :type => 'text/css'}
    = stylesheet_link_tag :all
    = javascript_include_tag 'jquery'
    = csrf_meta_tag
  %body
    %section#body
      %nav#nav_user
        %ul
          - if user_signed_in?
            - if current_user.admin?
              %li
                = User.active.count
                active
                \/
                = User.count
                total
            %li= link_to current_user.email, edit_user_path(current_user)
            %li= link_to "Sign out", signout_services_path
          - else
            %li= link_to "Sign in", '/auth/google'
          %li &nbsp;
      .clear
      %section#flash
        - flash.each do |key, value|
          .flash.round{:class => key}
            = value
      = yield
    %script
      = yield :page_javascript